### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by yaxu** [panavrin/livewriting_server#13]
Would love to experiment with your live writing things but can't get a foothold on getting it running.. `npm install` works but from there not sure what I should be running / looking at. any tips very much appreciated !

**Comment by panavrin** [comment]
Hi Alex.

No problem.

Btw this is a code repository of the server that i run. Not liveweiting api.

The repo for livewriting can be installed with 'npm install livewriting' or
see the code in the other github repo.

https://github.com/panavrin/livewriting?files=1

Npm link is here.

https://www.npmjs.com/package/livewriting

If you download the repo it will have a two examples html files in demo
folder.
It does not have a formal instruction yet but i will be more than happy to
answer any questions and update insyruction soon.

The server repository fyi require mongodb running to test in your computer
and node lib/server_mongo.js should run the local version of the website(
echobin.com)

Let me know immediately if you have any question.

Thanks!!

Sang

**Comment by yaxu** [comment]
Ace thanks very much, Sang! Will let you know how I get on.

I'll close this issue, then.
